### ISSUE TITLE
기획 논의 및 주간회의 요청 

### ISSUE THREAD

**Issue by Man-jae** [CWT-Study/yeohanglog-android#16]
## 개요
- 미비된 기능에 대한 기획 논의 필요.
- 서버 구현 공유

## 논의사항
@ckdgml6556 @springbb @DevNimo @bellKong @kha9920 
여행 일정 작성화면의 가계부 및 사진목록 화면에 대한 기획 확립과 디자인 초안이 필요합니다.
금주 금요일 모여서 미비된 기획 정의하고 슬슬 서버에서 필드 관련해서 공유가 필요할 것 같습니다.

**Comment by ckdgml6556** [comment]
@Man-jae @springbb @DevNimo @bellKong  @kha9920 
이번주 금요일날 모여서 얘기 하면 될 것 같습니다.
현재 서버는 정확한 필드까지는 정의하지 못하였고 어떤 API가 필요할지 정도만 정리하였습니다.
