### ISSUE TITLE
[UI] 여행 일정 - TripPlanDay 화면 추가 및 수정

### ISSUE THREAD

**Issue by kha9920** [CWT-Study/yeohanglog-android#40]
## 개요
- #2 - 화면 역할 분담

## 진행사항
- [x] 여행 일정 일별로 나누어지는 item 화면 추가
- [x] 여행 일정 일별로 나누어지는 item 화면 안의 RecyclerView item 화면 수정
- [ ] 여행 일정 일별 화면에 더미데이터 추가
- [ ] 여행 일정 일별 화면 안의 item 화면에 더미데이터 추가

**Comment by Man-jae** [comment]
해당 이슈는 화면 재조정으로 인해 close 하겠습니다.
