### ISSUE TITLE
검색화면 기획

### ISSUE THREAD

**Issue by Man-jae** [CWT-Study/yeohanglog-android#5]
## 개요
메인화면에서 사용할 검색탭의 상세 기획 및 UI 디자인 필요

## 기획
@ckdgml6556 @bellKong
해당 화면에 대한 상세한 기획이 필요합니다.

## 디자인
@springbb 
기획 완료시 진행하도록 하겠습니다.

## UI
디자인 완료시 진행하도록 하겠습니다.

위 담당자분들은 해당 이슈 확인 해주시고, 현재 이슈의 댓글로 의견 공유해주시면 됩니다.

**Comment by ckdgml6556** [comment]
이번주 금요일날 같이 논의하는 걸로 하겠습니다.

**Comment by Man-jae** [comment]
검색 화면에 대한 페이즈는 첫 릴리즈 이후로 변경하겠습니다.
