### ISSUE TITLE
MainActivity - MVVM 패턴 도입중

### ISSUE THREAD

**Issue by bellKong** [CWT-Study/yeohanglog-android#50]
## 진행사항
- View, ViewModel 클래스 생성 후 작성
- flagment, navigation 기능 구현
- Koin, LifeCycle 라이브러리 추가

## 현 기준 MVVM패턴 참고사이트
- https://medium.com/hongbeomi-dev/aac%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-mvvm-pattern%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%9C-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EC%95%B1-%EB%A7%8C%EB%93%A4%EA%B8%B0-1d6d73689bd0

**Comment by Man-jae** [comment]
@bellKong 
https://medium.com/@joongwon/android-aac%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-mvvm-%ED%8C%A8%ED%84%B4-e24a685fc25d

개인 앱 만들때 참고했던 AAC 활용 MVVM 패턴 예제

**Comment by Man-jae** [comment]
초기 MVVM 구조 잡으면서 Clean Architecture 까지 같이 도입하는게 좋을것 같아서 추가로 참고했던 예제 같이 올립니다.

https://academy.realm.io/kr/posts/clean-architecture-in-android/
https://woowabros.github.io/experience/2019/01/17/baeminapp-clean-architecture.html

위 두 예제는 참고용으로만 사용하고, 케바케라서 시간날때 우리 방식으로 구조잡는게 좋을 것 같습니다. 
참고만 하세요.

**Comment by Man-jae** [comment]
#54 이슈로 최신 관리하기 때문에 해당 이슈는 종료합니다.
