### ISSUE TITLE
MainActivity - MVVM 패턴 도입중 ( 100% )

### ISSUE THREAD

**Issue by bellKong** [CWT-Study/yeohanglog-android#54]
## 개요
- #50 참고

## 진행상황
- View, ViewModel 기본 구조 적용 완료
- ViewModel 데이터 재정의
- Model 추가 예정 

## 상세
MainActivity에 MVVM패턴 적용 80% 완료하였으며 
현재 구조는 MainActivity ( View ) - MainViewModel ( ViewModel ) <-> ViewModelModule 로 구성되어 있습니다.
후에 Model ( Repository ) 추가할 예정이며, 상기 내용 중 말 그대로 기본 구조만 적용하였기 때문에 재수정 작업이 필요합니다.

## 마무리
- MainHomeFragment의 MVVM구조를 짜게 되면서 Model쪽이 정의가 되었기 때문에
MainActivity, MainViewModel쪽만 재차 수정하였습니다.

## 수정사항
- BaseActivity : binding 변수 부분 삭제
- MainActivity : selectListner 원복, binding 추가
- MainViewModel : userRepository 추가

**Comment by Man-jae** [comment]
@bellKong 
BaseActivity 에서 binding 하는 방식을 학습후에 조금 수정해야할 것 같습니다.
