### ISSUE TITLE
MainHomeFragment - MVVM 패턴 적용 100%

### ISSUE THREAD

**Issue by bellKong** [CWT-Study/yeohanglog-android#56]
## 개요
- MainHomeViewMVVM패턴 적용
- View <-> ViewModel <-> Data ( repository [DataMoel, Database ] ) 로 구성

## 진행사항
- View
- [x] Binding 작업
- [x] viewModel 연결
- [x] observe 작업
- [x] adapater 작업

- ViewModel
- [x] repositoty 연결

- Model
- [x] Data Model 생성
- [x] Data Dao 생성
- [x] Database 생성
- [x] Repository 생성

## 상세
- 우선 MainHomeFragment에 MVVM패턴을 적용하였으며,
 이전에 MainActivit에서 작업을 못한 Model 쪽까지 적용하였으니 추후 상기내용을 바탕으로 MainActivit 수정 들어가겠습니다.

- MVVM패턴을 적용 전 소스는 삭제하지 않고 클래스를 새로 생성하여 적용하였습니다.

- 기존 MainAcitivt에 적용하였던 MVVM패턴과 다른 방식을 사용하였으며 참조한 사이트는 밑에 참조하였습니다

- 작업한 내용은 아래와 같습니다.
위치 : Data - local - dao
* TripDao
* TripLogDao

위치 : Data - local
* Trip
* TripDatabase
* TripLog
* TripLogDatabase
* UserDatabase

위치 :  Data - repository
* TripLogRepository
* TripRepository
* User Repository

위치 : presentation - main - adpater
* MainHomeAdapter
* MainHomeDiffCallback

위치 : presentation - main - fragment
* MainHomeFragment

위치 : presentation - main - viemodel
* MainHomeViewModel

## 참조
https://doitddo.tistory.com/52?category=855312

**Comment by Man-jae** [comment]
멋져요 :)
